name: Devops real project 1

on:
  push:
    branches: ["main"]
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code 
        uses: actions/checkout@v4

      - name: Python setup
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies 
        run: pip install -r requirements.txt
        
      - name: Formatting test
        run: black .
      
      - name: Lint test
        run: flake8 .
      
      - name: Static analysis 
        run: bandit -r .
    
      - name: Unit test
        run: python test_app.py

      - name: Dokerhub login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }} #Error rectified
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/devops-real-1 .

      - name: Push docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/devops-real-1
